### ISSUE TITLE
No way to remove dead objects from the pool

### ISSUE THREAD

**Issue by grantsheppard** [chanks/pond#1]
I'm using Pond to wrap Postgres connections. Occasionally a connection will die, for example: -

`PG::ConnectionBad - PQsocket() can't get socket descriptor`

However since the connection is always returned to the pool, it's still accessible.

I can't see anyway to tell the pool to remove a dead object and have it initialise a new one to refill the pool up to capacity.

**Comment by chanks** [comment]
Hmm, that's a reasonable request. Not sure what the API should be,
though...?

**Comment by grantsheppard** [comment]
It's a bit easier if you're only dealing with connections as you can simply execute some arbitrary SQL against a connection (either on checkin or checkout) to determine whether it's 'live' or not. Gets a bit trickier when you're dealing with objects of any type though.

Maybe check for the presence of a `is_ok?` method or something similar? If it exists then it could be called to determine whether to return the object to the pool or not?

**Comment by chanks** [comment]
Maybe. Or have a thread-local accessor on the pool object called something
like detach_object_on_return, or rescue a special error raised inside the
block or something. Hmm.

**Comment by grantsheppard** [comment]
Not sure whether either of these would work so well when you don't own the object being pooled though, e.g. a db connection. Guess you could wrap the object with one that catches any errors and re-raises them as a special predefined error or sets the detach_object_on_return to true...

I'm still relatively new to Ruby so not sure how else you'd do this?

**Comment by chanks** [comment]
The code manipulating the object seems like the reasonable place for the logic to determine whether it should be kept, right? For example (pseudocode):

``` ruby
$pool = Pond.new { PG::Connection.new }

$pool.checkout do |connection|
  begin
    connection.execute "SELECT * FROM table"
  rescue PG::ConnectionError => e
    # Remove bad connections from the pool.
    if e.message =~ /can't get socket descriptor/
      $pool.detach_current_object_on_checkin = true
    end
    raise # Bubble up exception
  end
end
```

Another alternative would be to allow the provision of a block that would run when an object is checked out, and it could return false or raise an error if the object shouldn't be used. For example:

``` ruby
$pool.before_checkout do |connection|
  connection.execute "SELECT 1" # Will raise an error if the connection has been lost.
end
```

That feels a little iffy to me, though. It's logic that would have to be performant enough that it could run on every checkout without noticeable issues. It also might be complicated for Pond to be able to run this code without holding the pool's mutex while the block runs, which would make it a source of contention.

**Comment by grantsheppard** [comment]
Yep, I also like the first approach - this way it's entirely up to the
client code using the pooled object to make the determination as to whether
the object is still valid after completing.

Nice library btw, very concise and useful (as is Que where I'm using it).

**Comment by chanks** [comment]
Thank you!

I just pushed to a branch called detach-on-checkin that implements a Pond#detach_on_checkin= accessor, would you try it out and let me know what you think? I feel good about the implementation, if it works for you, but I feel like there's a better name for this than "detach" - that was just the first thing I thought of. I might rename it to "remove_on_checkin", I don't know. Suggestions welcome :smile:

**Comment by grantsheppard** [comment]
Cool, will have a look and let you know :-)

**Comment by tpitale** [comment]
PR #2 may resolve this issue.

**Comment by chanks** [comment]
0.2.0 was just released with support for a detach_if option, so I'm going to close this.
