### ISSUE TITLE
Provide a list of different connections

### ISSUE THREAD

**Issue by archan937** [chanks/pond#3]
Hi,

Is it possible to provide a list of hosts to which the pool will connect to randomly? (unless the connection is dead of course)

Some pseudo code:

```
Pond.wrap(:hosts => ["localhost:1234", "localhost:1235", "localhost:1236"]) {|host| Redis.new host}
```

Thanks.

**Comment by chanks** [comment]
Not sure if you figured this out, but you could do:

``` ruby
Pond.wrap{ Redis.new(["localhost:1234", "localhost:1235", "localhost:1236"].sample) }
```

**Comment by archan937** [comment]
Not really sure, I want to make a connection to a sharded cluster. If one of the server is down for some kind of reason, I want to connect to one of the other servers.

I am not that familiar with these kind of connections but thought maybe that Pond could be part of the solution.

**Comment by archan937** [comment]
Thanks, Chris. I like the way how Pond is so minimalistic. This should be sufficient enough, I think

https://github.com/archan937/clickhouse/commit/b05d0d85705e5fee25e9165f797e66aeb1c7e416

Cheers ;)

**Comment by chanks** [comment]
No problem! Glad you found it useful.
